server.port: 8074
spring.application.name: api-gateway

spring:
  cloud:
    gateway:
      routes:
        - id: user_details
          uri: lb://USER-DETAILS-MICROSERVICE
          predicates:
            - Path=/api/v1/users/{id}

        - id: user_career_details
          uri: lb://USER-CAREER-MICROSERVICE
          predicates:
            - Path=/api/v1/user-career/{id}
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka