server.port: 8074
spring.application.name: api-gateway

spring:
  cloud:
    gateway:
      routes:
        - id: user_details
          uri: lb://USER-DETAILS-MICROSERVICE
          predicates:
            - Path=/api/v1/users/{id}
          filters:
            - SetPath=/api/v1/users/{id}
            - name: CircuitBreaker
              args:
                name: myCircuitBreaker
                fallbackUri: forward:/api/v1/users/fallback

        - id: user_career_details
          uri: lb://USER-CAREER-MICROSERVICE
          predicates:
            - Path=/api/v1/user-career/{id}
            -
management.tracing.sampling.probability: 1.0