server.port: 8073
spring.application.name: user-microservice

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always


resilience4j:
  circuitbreaker:
    instances:
      userDetailsServiceCircuitBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

  retry:
    instances:
      userCareer:
        maxRetryAttempts: 3
        waitDuration: 5s

  reatelimiter:
    instances:
      userStatus:
        registerHealthIndicator: false
        limitForPeriod: 10s
        timeoutDuration: 3s