server.port: 8072
spring.application.name: user-career-microservice
management.tracing.sampling.probability: 0.0
spring:
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh